AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create vpc
Mappings:
  VpcCidrs:
    publicsubnet1:
      cidr: 10.0.10.0/24
    publicsubnet2:
      cidr: 10.0.11.0/24
    vpc:
      cidr: 10.0.0.0/16

Outputs:
  VpcId:
    Value:
      Ref: Vpc
    Export:
      Name: VpcId
  PublicSubnetAz1:
    Value:
      Ref: PublicSubnetAz1
    Export:
      Name: PublicSubnetAz1
  PublicSubnetAz2:
    Value:
      Ref: PublicSubnetAz2
    Export:
      Name: PublicSubnetAz2

Resources:
  AttachGateway:
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: Vpc
    Type: AWS::EC2::VPCGatewayAttachment
  InternetGateway:
    Properties:
      Tags:
        - Key: Name
          Value: vpc-igw
    Type: AWS::EC2::InternetGateway
  PublicSubnetAz1:
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 0
        - Fn::GetAZs: ""
      CidrBlock:
        Fn::FindInMap:
        - VpcCidrs
        - publicsubnet1
        - cidr
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: vpc-subnet-public-1
    Type: AWS::EC2::Subnet
  PublicSubnetAz2:
    Properties:
      AvailabilityZone:
        Fn::Select:
        - 1
        - Fn::GetAZs: ""
      CidrBlock:
        Fn::FindInMap:
        - VpcCidrs
        - publicsubnet2
        - cidr
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: vpc-subnet-public-2
    Type: AWS::EC2::Subnet
  PubSubnet1RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnetAz1
    Type: AWS::EC2::SubnetRouteTableAssociation
  PubSubnet2RouteTableAssociation:
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnetAz2
    Type: AWS::EC2::SubnetRouteTableAssociation
  PublicRouteTable:
    Properties:
      VpcId:
        Ref: Vpc
      Tags:
        - Key: Name
          Value: vpc-routetable-public
    Type: AWS::EC2::RouteTable
  PublicRouteViaIgw:
    DependsOn: AttachGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
      RouteTableId:
        Ref: PublicRouteTable
    Type: AWS::EC2::Route
  Vpc:
    Properties:
      CidrBlock:
        Fn::FindInMap:
        - VpcCidrs
        - vpc
        - cidr
      Tags:
        - Key: Name
          Value: vpc-1
    Type: AWS::EC2::VPC